# fly.toml app configuration file generated for long-game on 2024-01-16T21:03:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "long-game"
primary_region = "iad"

[env]
DATABASE_FILE = "file:/data/database.sqlite"
HOST = "https://api.long-game.gfor.rest"
UI_HOST = "https://long-game.gfor.rest"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[http_service.concurrency]
type = "connections"
hard_limit = 10000
soft_limit = 10000

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[mounts]
source = "long_game_data"
destination = "/data"
