name = "prod-long-game-public-api-service"
compatibility_date = "2025-01-01"
main = "./index.ts"
account_id = "5f843fcad78a2f4e1fee091c1d6c21ab"

compatibility_flags = ["nodejs_compat"]


[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
UI_ORIGIN = "https://play.rout.games"
API_ORIGIN = "https://api.rout.games"
NODE_ENV = "production"
EMAIL_FROM = "noreply@rout.games"

[[services]]
binding = "PUBLIC_STORE"
service = "prod-long-game-db-service"
entrypoint = "PublicStore"

[[services]]
binding = "ADMIN_STORE"
service = "prod-long-game-db-service"
entrypoint = "AdminStore"

[[durable_objects.bindings]]
name = "GAME_SESSION_STATE"
class_name = "GameSessionState"

[[migrations]]
tag = "v1"
new_classes = ["GameSessionState"]
